"""something

Revision ID: 13df0f4e351a
Revises: 
Create Date: 2022-12-31 22:36:59.031941

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '13df0f4e351a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('return_duration', sa.Integer(), nullable=True))
        batch_op.drop_column('return_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('return_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('return_duration')

    # ### end Alembic commands ###
