"""added return time in rent table

Revision ID: ce1bfa23f2c8
Revises: 7353f72f1da5
Create Date: 2022-12-31 19:38:55.464164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce1bfa23f2c8'
down_revision = '7353f72f1da5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('return_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rent', schema=None) as batch_op:
        batch_op.drop_column('return_time')

    # ### end Alembic commands ###
